### ISSUE TITLE
Undefine 'create_world'

### ISSUE THREAD

**Issue by aslaq** [fogleman/Craft#157]
Hello,

I seem to be getting this error when I try to use builder.py

Traceback (most recent call last):
  File "server.py", line 200, in run
    self.dequeue()
  File "server.py", line 208, in dequeue
    func(*args, **kwargs)
  File "server.py", line 301, in on_data
    func(client, *args)
  File "server.py", line 377, in on_block
    previous = self.get_block(x, y, z)
  File "server.py", line 274, in get_block
    return self.get_default_block(x, y, z)
  File "server.py", line 263, in get_default_block
    chunk = self.world.get_chunk(p, q)
  File "/home/ameoba/Craft/world.py", line 44, in get_chunk
    chunk = self.create_chunk(p, q)
  File "/home/ameoba/Craft/world.py", line 39, in create_chunk
    return dll_create_world(p, q)
  File "/home/ameoba/Craft/world.py", line 18, in dll_create_world
    dll.create_world(p, q, WORLD_FUNC(world_func), None)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: ./world: undefined symbol: create_world

Am not sure what I am missing. Noone else seemed to have encountered the error before....

**Comment by fogleman** [comment]
You have to compile the world dll as shown here:

https://github.com/fogleman/Craft/blob/master/world.py#L1-L2

**Comment by aslaq** [comment]
The problem is there is a .data segment so I have to compile with -fPIC - which results in the initial error.

Error(both with gcc and clang)

Craft$ clang -std=c99 -O3 -shared -o world -I src -I deps/noise deps/noise/noise.c src/world.c
/usr/bin/ld: /tmp/noise-459bb6.o: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
/tmp/noise-459bb6.o: error adding symbols: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by fogleman** [comment]
What error do you get when you add -fPIC?

**Comment by aslaq** [comment]
I get the very first error - actually I compiled with -fPIC before I opened this issue

**Comment by fogleman** [comment]
Not sure what's wrong then.
