### ISSUE TITLE
the builder.py and the server.py and the world.py giving error

### ISSUE THREAD

**Issue by TheHackerClown** [fogleman/Craft#280]
in world.py - Traceback (most recent call last):
  File ".\Craft-master\world.py", line 7, in <module>
    dll = CDLL('./world')
  File ".\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module '.\Craft-master\world' (or one of its dependencies). Try using the full path with constructor syntax.

in builder.py- Traceback (most recent call last):
  File ".\Craft-master\builder.py", line 248, in <module>
    main()
  File ".\Craft-master\builder.py", line 189, in main
    client = get_client()
  File ".\Craft-master\builder.py", line 185, in get_client
    client = Client(host, int(port))
  File ".\Craft-master\builder.py", line 145, in __init__
    self.conn.connect((host, port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

in server.py - giving error of print statement like invalid syntax

Please fix them as i wanted to play this game asap

**Comment by Python-Sargent** [comment]
looks like an error with the server not having the correct dependencies (or client).
